### ISSUE TITLE
I can't training on GPU

### ISSUE THREAD

**Issue by zrqi** [MarekKowalski/DeepAlignmentNetwork#42]
Hi:
I'm trying to use the DANtraining.py to complete the training process about the code,but i find the training is so slow,and it seems that it did not use GPU for training.Why is this happening?

**Comment by MarekKowalski** [comment]
Hi,

Most likely you need to set the correct device in theano settings.
Here is the guide to doing that:
http://deeplearning.net/software/theano/library/config.html

I believe you will also need to have CUDA installed.

Best regards,

Marek

**Comment by zrqi** [comment]
Thank you for your reply. In your way, I found that my theano was not configured on the GPU and is now running on the GPU. I have a few more questions about the model that I want to ask you: according to the model you trained to put on the Google drive, its name is 'DAN.npz', but during my training, the generated model names are similar 'network_00289_2018-09-21-13-30.npz'. Is this the model that can finaly to be tested? Another question is, during training, does the size of the model change with the number of iterations? Because in my training process ,the 'out of memory' often occurs.

**Comment by zrqi** [comment]
And i I just discovered that during my training process the validation error is lower than train error:
Starting epoch 6
Validation error: 0.0578055562641
Train error: 0.0803057433784
Do you know why this happens?

**Comment by MarekKowalski** [comment]
Yes, the "network_.." files are of the same type as the DAN.npz file. The DAN.npz file is only named so, because that model name is used in the paper. 

As for out of memory errors: if it concerns the GPU than you can try reducing the batch sizes. If it concerns the computer's memory then you might want to increase the amount of virtual memory or RAM in your computer. Having said that, once the training starts there should be no significant fluctuations in memory usage.

Not sure why the validation error is lower than training error in your particular case - perhaps the examples in the validation set are particularly easy?

**Comment by zrqi** [comment]
Sorry to bother you again，when i use the Theano to train the net,it just use the GPU 0,do you know someway allow  me to design the number of GPU?

**Comment by MarekKowalski** [comment]
Hi,

You can set the number of the GPU in theano settings. Not sure about using multiple GPUs at the same time. Please refer to theano documentation for this.

Best regards,

Marek

**Comment by zrqi** [comment]
I'm sorry to have noticed your reply so late. I successfully numbered the GPU according to the instructions. Thank you very much .
