### ISSUE TITLE
how can I visualize heatmap ? 

### ISSUE THREAD

**Issue by dedoogong** [MarekKowalski/DeepAlignmentNetwork#7]
I'm trying to see how the heatmap is generated and focusing on draw_landmarks_helper.
 def draw_landmarks_helper(self, landmark):
        img = T.zeros((1, self.img_shape[0], self.img_shape[1]))
        
        intLandmark = landmark.astype('int32')
        locations = self.offsets + intLandmark
        dxdy = landmark - intLandmark

        offsetsSubPix = self.offsets - dxdy
        vals = 1 / (1 + T.sqrt(T.sum(offsetsSubPix * offsetsSubPix, axis=1) + 1e-6))

        img = T.set_subtensor(img[0, locations[:, 1], locations[:, 0]], vals)

        img2=T.cast(img,'uint8') 
        vals2=img2.eval()  << error!
        imshow("heatmap",vals2)
        return img

can you give me an advice on how to see the array or tensor?

thank you.

**Comment by MarekKowalski** [comment]
Unfortunately in theano you can't just visualize things like that. Try the code example below:

`from FaceAlignment import FaceAlignment
from ImageServer import ImageServer
import theano
import lasagne
import numpy as np
from matplotlib import pyplot as plt

faceAlignment = FaceAlignment(112, 112, 1, 2)
faceAlignment.loadNetwork('../DAN.npz')

datasetDir ="../data/"
challengingSet = ImageServer.Load(datasetDir + "challengingSet.npz")

inputImg, transform = faceAlignment.CropResizeRotate(challengingSet.imgs[1], challengingSet.initLandmarks[1])
inputImg = inputImg - faceAlignment.meanImg
inputImg = inputImg / faceAlignment.stdDevImg

theanoHeatmap = lasagne.layers.get_output(faceAlignment.layers["s1_img_landmarks"], deterministic=True)
heatmapFunction = theano.function([faceAlignment.data], [theanoHeatmap])
heatmap = heatmapFunction([inputImg])[0][0][0]

plt.imshow(heatmap)
plt.show()
`
In order to run this you need to have the "challengingSet.npz" file, the instructions for its creation are in the readme file. You can also subsitute the image from "challengingSet.npz" with any other image.

**Comment by dedoogong** [comment]
wow really thank you!
I applied your guide to CameraDemo.py

    def initializeNetwork(self):
        self.layers = self.createCNN()
        self.network = self.layers['output']
        
        self.prediction = lasagne.layers.get_output(self.network, deterministic=True)
        self.generate_network_output = theano.function([self.data], [self.prediction])

        self.theanoHeatmap = lasagne.layers.get_output(self.layers["s1_img_landmarks"], deterministic=True)
        self.heatmapFunction = theano.function([self.data], [self.theanoHeatmap])


    def processImg(self, img, inputLandmarks):
        inputImg, transform = self.CropResizeRotate(img, inputLandmarks)
        inputImg = inputImg - self.meanImg
        inputImg = inputImg / self.stdDevImg  
        heatmap = self.heatmapFunction([inputImg])[0][0][0] 
        return heatmap

and I finally succeeded in seeing the heatmap!

really thank you again!
